vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'

        property_image_miniature:
            uri_prefix: /images/miniature
            upload_destination: '%kernel.project_dir%/public/images/miniature'
