vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            delete_on_update: false
            delete_on_remove: false

        article_image_miniature:
            uri_prefix: /images/miniature_article
            upload_destination: '%kernel.project_dir%/public/images/miniature'
            delete_on_update: false
            delete_on_remove: false

        event_image:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'
            delete_on_update: false
            delete_on_remove: false

        event_image_miniature:
            uri_prefix: /images/miniature_event
            upload_destination: '%kernel.project_dir%/public/images/miniature_event'
            delete_on_update: false
            delete_on_remove: false
